version: '3'

services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/jenkins:lts'
    ports:
      - '127.0.0.1:9080:8080'
      - '127.0.0.1:9443:8443'
      - '127.0.0.1:50000:50000'
    volumes:
      - /home/jordi/data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
